name: Deploy to Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install and Build Client
        run: |
          cd client
          npm install
          npm run build

      - name: Upload via FTP
        run: |
          apt-get update && apt-get install -y lftp
          lftp -e "open ftp://${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}@theebookpublishing.com; mirror -R ./client/dist/ /public_html/; quit"
          